const hashingInput = document.getElementById('hashing')
const costInput = document.getElementById('cost')
const poolInput = document.getElementById('pool')
const powerInput = document.getElementById('power')
const coinsInput = document.getElementById('coins')
const mainform = document.getElementById('mainform')
const handleSubmit = (e) => {
    e.preventDefault()
    console.log(hashingInput.textContent)
    const hashing = parseFloat(hashingInput.value)
    const cost = parseFloat(costInput.value)
    const pool = parseFloat(poolInput.value)
    const coins = parseFloat(coinsInput.value)
    console.log(hashing * cost * pool * coins)
}
mainform.addEventListener("submit", handleSubmit)
