const hashingInput = document.getElementById('hashing')
const costInput = document.getElementById('cost')
const poolInput = document.getElementById('pool')
const powerInput = document.getElementById('power')
const hashingInput = document.getElementById('hashing')
const hashingInput = document.getElementById('hashing')